name: Générer le fichier models-index.md

on:
  push:
    branches: [main]

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Générer le fichier models-index.md
        run: |
          echo "# Liste des modèles STL" > models-index.md
          echo "" >> models-index.md
          
          for dir in */ ; do
            # Exclure .github
            if [ "$dir" != ".github/" ]; then
              # Supprime le slash final
              name="${dir%/}"
              echo "- [${name}](./${name}/README.md)" >> models-index.md
            fi
          done

      - name: Vérifier les modifications
        id: changes
        run: |
          if git diff --quiet models-index.md; then
            echo "Aucun changement à commit."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Des changements détectés dans models-index.md"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit et push si nécessaire
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add models-index.md
          git commit -m "🔄 Mise à jour automatique de models-index.md"
          git push